spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_wpob
    username: wpob
    password: dhGKBljXVhLjhoX5
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
