### 사용자 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "wpob.ap-northeast-2.elasticbeanstalk.com",
  "password": "1z2x3c4v"
}

### 사용자 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "tester@email.com",
  "password": "1z2x3c4v"
}

### 게시글 생성

POST http://localhost:8080/posts
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTY1MTA3MiwiZXhwIjoxNjkxNjU0NjcyfQ.o0F87zHblxuiZ6vwlbhK6gzLia7DtSWq5aPr7ZsX340

{
  "title": "tester가 새 게시글을 생성합니다.",
  "content": "내용도 작성해 줍니다."
}

### 게시글 목록 조회

GET http://localhost:8080/posts?size=10&page=1
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTY1MTA3MiwiZXhwIjoxNjkxNjU0NjcyfQ.o0F87zHblxuiZ6vwlbhK6gzLia7DtSWq5aPr7ZsX340

### 특정 게시글 조회

GET http://localhost:8080/posts/8
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTY1MTA3MiwiZXhwIjoxNjkxNjU0NjcyfQ.o0F87zHblxuiZ6vwlbhK6gzLia7DtSWq5aPr7ZsX340

### 특정 게시글 수정

PATCH http://localhost:8080/posts/6
Content-Type: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTY1MTA3MiwiZXhwIjoxNjkxNjU0NjcyfQ.o0F87zHblxuiZ6vwlbhK6gzLia7DtSWq5aPr7ZsX340

{
  "title": "tester가 다른 사용자가 작성한 글을 수정합니다.",
  "content": "수정된 내용입니다."
}

### 특정 게시글 삭제

DELETE http://localhost:8080/posts/6
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTY1MTA3MiwiZXhwIjoxNjkxNjU0NjcyfQ.o0F87zHblxuiZ6vwlbhK6gzLia7DtSWq5aPr7ZsX340