### 회원가입 요청

POST http://localhost:8080/auth/signup
Content-Type: application/json;charset=UTF-8

{
  "email": "test@test.com",
  "password": "12341234"
}

### 로그인 요청

POST http://localhost:8080/auth/login
Content-Type: application/json;charset=UTF-8

{
  "email": "test@test.com",
  "password": "12341234"
}

### 게시글 생성 요청

POST http://localhost:8080/posts
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTI5NzIyNSwiZXhwIjoxNjkxMzAwODI1fQ.Ov_H9Fukqs15ZFfBnD9fzZAZlK-oZAW_rGfde61upYY
Content-Type: application/json;charset=UTF-8

{
  "title": "posts.http 게시글 제목입니다4",
  "content": "posts.http 게시글 생성 요청 내용입니다."
}

### 게시글 조회 요청(content 제외) - 페이지 정보 없이 요청

GET http://localhost:8080/posts
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTI5NzIyNSwiZXhwIjoxNjkxMzAwODI1fQ.Ov_H9Fukqs15ZFfBnD9fzZAZlK-oZAW_rGfde61upYY

### 게시글 조회 요청(content 제외) - 페이지 정보 포함 요청

GET http://localhost:8080/posts?size=3&page=2
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTI5NzIyNSwiZXhwIjoxNjkxMzAwODI1fQ.Ov_H9Fukqs15ZFfBnD9fzZAZlK-oZAW_rGfde61upYY

### 특정 게시글 조회 요청

GET http://localhost:8080/posts/2
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTI5NzIyNSwiZXhwIjoxNjkxMzAwODI1fQ.Ov_H9Fukqs15ZFfBnD9fzZAZlK-oZAW_rGfde61upYY


### 게시글 수정 요청

PATCH http://localhost:8080/posts
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTI5NzIyNSwiZXhwIjoxNjkxMzAwODI1fQ.Ov_H9Fukqs15ZFfBnD9fzZAZlK-oZAW_rGfde61upYY
Content-Type: application/json;charset=UTF-8

{
  "id": 2,
  "title": "postId 2번 글 수정",
  "content": "수정한 글의 내용입니다."
}

### 특정 게시글 삭제 요청

DELETE http://localhost:8080/posts/2
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiV1BPQiIsImlhdCI6MTY5MTI5NzIyNSwiZXhwIjoxNjkxMzAwODI1fQ.Ov_H9Fukqs15ZFfBnD9fzZAZlK-oZAW_rGfde61upYY
